### PR TITLE
Updates plus parallel processing for mandel_dd_aa.

### PR DESCRIPTION
**Pull request by marioroy**
Re: [Won't compile](https://github.com/josch/mandelbrot/issues/1) and [Enhancement - Enabling parallel via OpenMP](https://github.com/josch/mandelbrot/issues/2).

### CODE REVIEW

**Comment by josch** [comment]
Hi @marioroy! There is lots of good stuff in there -- thank you!

Would you like me to fix the remaining issues myself or would you like me to work with you through them and you update this pull request until everything is fine? You decide. :)

**Comment by marioroy** [comment]
Hi @josch,

Please feel free to do as you wish with this PR. The update bits were simply using "centerx" and "centery" as passed in versus hard-coded values. Ditto for maxiter. I gave OpenMP a try for mandel_dd_aa and computed 15360 8640 -0.75 0.0 1.0 (i.e. 1920x8 by 1080x8). I then opened the ppm file and scrolled around; simply wowed by the generated fractal.

OpenMP works beautifully. I needed to declare the vars inside the top loop so that each thread has it's own. Another way is passing private(var1, var2, ...) to the OpenMP pragma line.

Regards, Mario

**Comment by marioroy** [comment]
Fedora 32 lacks the libav-tools package (avconf). Fortunately, there is another way. I added `ffmpeg` usage to the README file.

Reference: [FFMPEG Images To Video Tutorial](https://linuxhint.com/ffmpeg_images_to_video_tutorial/)

**Comment by josch** [comment]
Thanks! The avconf call should be removed entirely. Back when I wrote this, there was still this awful ffmpeg/avconf split. For a good summary of the background read here: https://stackoverflow.com/a/9477756/784669 This split is long since over and also Debian/Ubuntu (the platform I'm using) ship ffmpeg instead of avconf again.

**Comment by marioroy** [comment]
Hi. It has been a while and think to close this pull request. I made a [Mandelbrot explorer](https://github.com/marioroy/mandelbrot-python) in Python using Numba and similarly using PyOpenCL and PyCUDA.

**Pull request closed without merging**
